name: Clojure CI

on:
  - push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run make ci-build in dev container
      uses: devcontainers/ci@v0.3
      with:    
               push: never
               runCmd: clj -T:build ci


